# 参数管理
首先关注只有一个隐藏层的多层感知机

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [6]:
net = nn.Sequential(nn.Linear(2, 10), nn.ReLU(), nn.Linear(10, 1))
X = torch.randn(1, 2)
net(X)

tensor([[0.6304]], grad_fn=<AddmmBackward0>)

In [8]:
# 可以把net简单的理解成一个list
print(net[0].state_dict())
print('-' * 50)
print(net[1].state_dict())
print('-' * 50)
print(net[2].state_dict())

OrderedDict([('weight', tensor([[ 0.0908, -0.3211],
        [ 0.3577,  0.0298],
        [ 0.2798,  0.2215],
        [-0.3288,  0.5381],
        [-0.4339, -0.1995],
        [ 0.1267,  0.0210],
        [-0.3011,  0.6287],
        [ 0.0179,  0.3910],
        [ 0.1185, -0.2769],
        [ 0.4483, -0.4368]])), ('bias', tensor([-0.4719,  0.0544, -0.3760, -0.6724,  0.4816,  0.6374,  0.2119,  0.1519,
         0.5913, -0.5480]))])
--------------------------------------------------
OrderedDict()
--------------------------------------------------
OrderedDict([('weight', tensor([[ 0.2271,  0.2390, -0.2177, -0.1952,  0.3145,  0.2331, -0.2545,  0.0176,
          0.2124,  0.2918]])), ('bias', tensor([0.2157]))])


In [11]:
net[2].weight

Parameter containing:
tensor([[ 0.2271,  0.2390, -0.2177, -0.1952,  0.3145,  0.2331, -0.2545,  0.0176,
          0.2124,  0.2918]], requires_grad=True)

In [12]:
net[2].bias

Parameter containing:
tensor([0.2157], requires_grad=True)

In [13]:
net[2].weight.data

tensor([[ 0.2271,  0.2390, -0.2177, -0.1952,  0.3145,  0.2331, -0.2545,  0.0176,
          0.2124,  0.2918]])

In [14]:
net[2].bias.data

tensor([0.2157])