# 池化层
- 池化层分为最大池化层和平均池化层两种方式
- 在池化层中，每个输入像素点的输出值都是一个统计值，而不是一个特定的像素点
- 池化层可以缓解卷积层对位置的敏感性，也就是说池化层往往作用于卷积层之后，如果输入图片像素矩阵发生了抖动或便宜，虽然经过卷积层发生了改变，但是池化层的输出矩阵不会发生改变
- 同样有窗口的大小、填充、步幅作为池化层的超参数
- 一般对池化层不做填充处理，所以池化层后的输出之和步幅、kernel大小有关
- 池化层不会输入通道和输出通道是相等的，也就是说不会想卷积层那样最后要把输出通道叠加起来

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i+p_h, j:j+p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i+p_h, j:j+p_w].mean()
    return Y

In [5]:
# 测试池化层
X = torch.arange(9).view(3, 3)
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [7]:
# 填充和步幅的应用
X = torch.arange(16, dtype=float).view(1, 1, 4, 4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]], dtype=torch.float64)

In [8]:
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]], dtype=torch.float64)

In [9]:
# 手动制定填充和步幅
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]], dtype=torch.float64)